services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rlt.rule=Host(`tracker.rawz06.fr`)"
      - "traefik.http.routers.rlt.entrypoints=websecure"
      - "traefik.http.routers.rlt.tls.certresolver=myresolver"
    networks:
      - web
    restart: always

networks:
  web:
    external: true

