name: Docker build

on:
  workflow_run:
    workflows: ["Nuxt Build"]
    types:
      - completed

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "NUXT_UI_PRO_LICENSE=${{ secrets.NUI_LICENSE_KEY }}" > .env
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Clean up .env file
      run: rm .env
